In [134]:
import numpy as np
from numpy import NaN as NA
import pandas as pd
from numpy.random import randn
from numpy.linalg import inv,qr, eig ,det ,svd

import matplotlib.pyplot as plt
import random

from pandas import DataFrame , Series

## Series

In [4]:
obj = Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [2]:
obj2 = Series([4,7,-5,3],index=['a','b',"c",'d'])

In [10]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [12]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
obj2[obj2>0]

a    4
b    7
d    3
dtype: int64

In [14]:
'b' in obj2

True

In [3]:
obj2_dict = obj2.to_dict()

In [4]:
obj2_dict

{'a': 4, 'b': 7, 'c': -5, 'd': 3}

In [5]:
obj2 = Series(obj2_dict)
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [7]:
'a' in obj2

True

In [10]:
sdata = {'aa':12,"dfas":444,"sag":13,'hh':68}

In [11]:
sdata

{'aa': 12, 'dfas': 444, 'hh': 68, 'sag': 13}

In [12]:
obj3 = Series(sdata)

In [13]:
obj3

aa       12
dfas    444
hh       68
sag      13
dtype: int64

In [32]:
states = list(sdata.keys())

In [33]:
states.remove('hh')
states.append('kk')

In [34]:
obj4 = Series(sdata ,index = states)

In [35]:
obj4

dfas    444.0
aa       12.0
sag      13.0
kk        NaN
dtype: float64

In [36]:
pd.isnull(obj4)

dfas    False
aa      False
sag     False
kk       True
dtype: bool

In [37]:
obj4.isnull()

dfas    False
aa      False
sag     False
kk       True
dtype: bool

In [38]:
obj3

aa       12
dfas    444
hh       68
sag      13
dtype: int64

In [42]:
print(obj4.name)

None


In [43]:
obj4.name = 'obj4'

In [44]:
print(obj4.name)

obj4


In [45]:
obj4.index

Index(['dfas', 'aa', 'sag', 'kk'], dtype='object')

In [46]:
obj4.index.name

In [47]:
obj4.index.name  = 'obj4_index'

## DataFrame

In [2]:
data = {'state':['ohio','ohio','ohio','nevada','nevada'],
        'year':[2000,2001,2002,2001,2002],
        'pop':[1.5,1.7,3.6,2.4,2.9]
       }

In [3]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['ohio', 'ohio', 'ohio', 'nevada', 'nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [4]:
frame = DataFrame(data)

In [5]:
frame

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [6]:
frame.state.name = 'test'

In [7]:
frame #changing  column name can't reflect on frame columns   

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [8]:
DataFrame(data, columns = [1,2,3])#没有这三列

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [9]:
DataFrame(data, columns = [])

Empty DataFrame
Columns: []
Index: []

In [11]:
frame['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

## 使用ix找到行

In [15]:
frame.ix[0]

pop       1.5
state    ohio
year     2000
Name: 0, dtype: object

In [16]:
frame['debt'] = 16.5

In [17]:
frame

pop   state  year  debt
0  1.5    ohio  2000  16.5
1  1.7    ohio  2001  16.5
2  3.6    ohio  2002  16.5
3  2.4  nevada  2001  16.5
4  2.9  nevada  2002  16.5

In [18]:
np.arange(5.)

array([ 0.,  1.,  2.,  3.,  4.])

In [19]:
frame['debt'] = np.arange(5)

In [20]:
frame

pop   state  year  debt
0  1.5    ohio  2000     0
1  1.7    ohio  2001     1
2  3.6    ohio  2002     2
3  2.4  nevada  2001     3
4  2.9  nevada  2002     4

## Series 有索引 并且按照索引创建列

In [22]:
val = Series([1,2,5.6] , index=[2,3,5])

In [23]:
frame['debt_'] = val

In [24]:
frame

pop   state  year  debt  debt_
0  1.5    ohio  2000     0    NaN
1  1.7    ohio  2001     1    NaN
2  3.6    ohio  2002     2    1.0
3  2.4  nevada  2001     3    2.0
4  2.9  nevada  2002     4    NaN

In [25]:
need_to_compare_val = Series([1,2,3])

In [26]:
val == need_to_compare_val

ValueError: Can only compare identically-labeled Series objects

In [27]:
need_to_compare_val = Series([1,2,3],index =[1,2,3])

In [28]:
val == need_to_compare_val

ValueError: Can only compare identically-labeled Series objects

* an only compare identically-labeled Series objects
* 必须完全相等的index才能比较

In [29]:
val == val

2    True
3    True
5    True
dtype: bool

In [30]:
need_to_compare_val.index = [2,3,5]

In [31]:
val == need_to_compare_val

2     True
3     True
5    False
dtype: bool

In [32]:
val[_]

2    1.0
3    2.0
dtype: float64

## 等长不等index的单列的Frame进行比较

In [35]:
val = DataFrame([1,2,5.6] , index=[2,3,5])

In [36]:
val

0
2  1.0
3  2.0
5  5.6

In [37]:
val1 = DataFrame([14,27,56] , index=[1,2,3])

In [38]:
val1

0
1  14
2  27
3  56

In [41]:
val [val1]

ValueError: Must pass DataFrame with boolean values only

* 切片传进去的是布尔值坐标

## 比较两个DataFrame的条件

In [48]:
val_ = DataFrame({0:[14,27,56],1:[1,2,3]} , index=[2,3,5])

In [49]:
val_

0  1
2  14  1
3  27  2
5  56  3

In [50]:
val

0
2  1.0
3  2.0
5  5.6

In [55]:
val  == val_[0].to_frame()

0
2  False
3  False
5  False

## 根据布尔值索引判断选中的行

In [57]:
val_

0  1
2  14  1
3  27  2
5  56  3

In [61]:
type(val  == val_[0].to_frame())

pandas.core.frame.DataFrame

In [64]:
val_[0] == 14

2     True
3    False
5    False
Name: 0, dtype: bool

In [84]:
val_[Series([True,True,False],index=[2,3,5])] 

0  1
2  14  1
3  27  2

In [85]:
val_[Series([True,True,False],index=[1,3,5])] 

/home/zhanghui/py35/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

* 应用boolean序列的时候 ， 索引必须完全相同

In [90]:
val_[0].to_frame()[Series([True,True,False],index=[1,3,5]).to_frame()] 

0
2   NaN
3  27.0
5   NaN

* 除非被筛选的是单列

## 新列被赋予以一个Series

In [94]:
val_

0  1
2  14  1
3  27  2
5  56  3

In [95]:
val_['wo'] = Series([1,2,3], index =[1,2,3])

In [97]:
val_

0  1   wo
2  14  1  2.0
3  27  2  3.0
5  56  3  NaN

* 按照索引配给值

## 嵌套字典的输入

In [2]:
pop = {'Nevada':{2001:2.4,2002:2.9}, 'Ohio':{2000:1.5 ,2001:1.7,2002:3.6}}

In [3]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [4]:
frame3 = DataFrame(pop)

In [5]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [6]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [7]:
DataFrame(pop , index= [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [8]:
pdata = {
    'Ohio':frame3['Ohio'][:-1] , 
    'Nevada':frame3['Nevada'][:2]  
    
}

In [9]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [10]:
frame3.index.name = 'index'
frame3.columns.name = 'state'



In [12]:
frame3

state  Nevada  Ohio
index              
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [13]:

frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

## 索引对象

In [14]:
obj = Series(range(3) , index=['a','b','c'])

In [16]:
index = obj.index

In [17]:
index

Index(['a', 'b', 'c'], dtype='object')

In [18]:
index = pd.Index(np.arange(3))

In [19]:
index

Int64Index([0, 1, 2], dtype='int64')

In [20]:
obj = Series([1,2.4,3],index = index)

In [21]:
obj

0    1.0
1    2.4
2    3.0
dtype: float64

In [22]:
obj.index == index 

array([ True,  True,  True], dtype=bool)

In [23]:
obj.index is index 

True

In [24]:
2001 in frame3.index

True

## 两个索引之间的操作

In [25]:
index1 = pd.Index(np.arange(3))

In [26]:
index2 = pd.Index([2,3,4])

In [27]:
index2.append(index1)

Int64Index([2, 3, 4, 0, 1, 2], dtype='int64')

In [28]:
index1.diff(index2)

AttributeError: 'Int64Index' object has no attribute 'diff'

In [29]:
index1.union(index2)

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [30]:
index2.union(index1)#自动排序

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [31]:
index1.intersection(index2)

Int64Index([2], dtype='int64')

In [32]:
index1.isin([1,2])

array([False,  True,  True], dtype=bool)

In [33]:
index1.delete(1)

Int64Index([0, 2], dtype='int64')

In [34]:
index1.delete([0,1])

Int64Index([2], dtype='int64')

In [36]:
index1.insert(1,19)

Int64Index([0, 19, 1, 2], dtype='int64')

In [37]:
index3 = index1.insert(1,1)
index3

Int64Index([0, 1, 1, 2], dtype='int64')

In [38]:
index3.unique()

Int64Index([0, 1, 2], dtype='int64')

## reindex 重新索引

In [39]:
obj = Series([4.5, 7.3, -5.3 , 3.6 ], index=['d','b','a','c'])

In [40]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [41]:
obj2

a   -5.3
b    7.3
c    3.6
d    4.5
e    NaN
dtype: float64

In [42]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.3
c    3.6
d    4.5
e    0.0
dtype: float64

In [43]:
obj3 = Series(['blue' , 'purple' ,'yellow'],index = [0,2,4])

In [44]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [45]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [46]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a', 'b', 'd'], columns=['Ohio','Texas','California'])

In [47]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [48]:
frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   NaN    NaN         NaN
d   6.0    7.0         8.0

In [49]:
states = ['Texas','Utah','California']

In [50]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
d      7   NaN           8

In [52]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [51]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill', columns=states )

ValueError: index must be monotonic increasing or decreasing

In [53]:
frame.ix[['a', 'b', 'c', 'd'] , states]

Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    NaN   NaN         NaN
d    7.0   NaN         8.0

In [54]:
_.ffill()

Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [55]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd','e'])

In [56]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [57]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [71]:
data = DataFrame(
    np.arange(16).reshape((4,4)),
    index=['Ohio', 'Colifornia', 'Utah', 'New York'],
    columns=['one','two','three','four']
)

In [72]:
data

one  two  three  four
Ohio          0    1      2     3
Colifornia    4    5      6     7
Utah          8    9     10    11
New York     12   13     14    15

In [73]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colifornia    4    5      6     7
New York     12   13     14    15

In [74]:
data

one  two  three  four
Ohio          0    1      2     3
Colifornia    4    5      6     7
Utah          8    9     10    11
New York     12   13     14    15

In [63]:
del data['four']

In [75]:
data

one  two  three  four
Ohio          0    1      2     3
Colifornia    4    5      6     7
Utah          8    9     10    11
New York     12   13     14    15

In [76]:
data.drop('two',axis = 1)

one  three  four
Ohio          0      2     3
Colifornia    4      6     7
Utah          8     10    11
New York     12     14    15

In [77]:
data

one  two  three  four
Ohio          0    1      2     3
Colifornia    4    5      6     7
Utah          8    9     10    11
New York     12   13     14    15

In [78]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])      

In [79]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [80]:
obj['b']

1.0

In [82]:
obj[2:4]  #Python方式的切片

c    2.0
d    3.0
dtype: float64

In [83]:
obj['a':'b'] #利用标签的切片方式

a    0.0
b    1.0
dtype: float64

In [84]:
data

one  two  three  four
Ohio          0    1      2     3
Colifornia    4    5      6     7
Utah          8    9     10    11
New York     12   13     14    15

In [85]:
data[data['one']>5]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [108]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])      

In [109]:
s2 = Series([4.3, 1.3, -1.5, 3.4, 1.5], index=['a', 'c', 'e', 'f', 'g'])      

In [110]:
s1+s2

a    11.6
c    -1.2
d     NaN
e     0.0
f     NaN
g     NaN
dtype: float64

In [111]:
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [112]:
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [113]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [114]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [116]:
df1.add(df2 ,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [117]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## DataFrame和Series之间的运算

In [2]:
arr = np.arange(12.).reshape(3,4)

In [3]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [4]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [5]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [6]:
frame = DataFrame(np.arange(12.).reshape(4, 3), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [8]:
series = frame.iloc[0]

In [10]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [9]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [11]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [13]:
series2 = Series(range(3), index=['b', 'e', 'f'])

In [15]:
series2

b    0
e    1
f    2
dtype: int64

In [16]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [17]:
series3 = frame['d']

## 在列上运算广播

In [18]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [19]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用与映射

In [20]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [21]:
frame

b         d         e
Utah   -0.597188  0.733078 -0.950428
Ohio    2.619808 -2.114980  0.494577
Texas   0.976557 -0.912820  1.193944
Oregon -1.131938 -0.681508  0.145509

In [23]:
np.abs(frame) #numpy的ufunc应用于pandas对象

b         d         e
Utah    0.597188  0.733078  0.950428
Ohio    2.619808  2.114980  0.494577
Texas   0.976557  0.912820  1.193944
Oregon  1.131938  0.681508  0.145509

In [25]:
type(np.abs(frame))# 注意应用之后还是返回一个DataFrame对象

pandas.core.frame.DataFrame

In [26]:
f = lambda x:x.max() - x.min() #x是一行或者一列

In [27]:
frame.apply(f)

b    3.751745
d    2.848058
e    2.144372
dtype: float64

In [28]:
frame.apply(f,axis=1)

Utah      1.683505
Ohio      4.734787
Texas     2.106765
Oregon    1.277447
dtype: float64

In [29]:
def f(x):
    return Series([x.max(), x.min()], index=['min','max'])

In [30]:
frame.apply(f)

b         d         e
min  2.619808  0.733078  1.193944
max -1.131938 -2.114980 -0.950428

In [31]:
format = lambda x:'%.2f'%x

In [32]:
frame.applymap(format)

b      d      e
Utah    -0.60   0.73  -0.95
Ohio     2.62  -2.11   0.49
Texas    0.98  -0.91   1.19
Oregon  -1.13  -0.68   0.15

In [33]:
frame['e'].map(format)

Utah      -0.95
Ohio       0.49
Texas      1.19
Oregon     0.15
Name: e, dtype: object

## 排序和排名

In [34]:
obj = Series(range(4), index=list('dabc'))

In [35]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [36]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [40]:
frame = DataFrame(np.arange(8).reshape(2,4),  columns=list('dabc'),index=['three', 'one'])

In [41]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [42]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [43]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [44]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [45]:
obj = Series([4, 7, -3, 2])

In [47]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [48]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])

In [50]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [52]:
obj.sort_index()

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [53]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [54]:
frame = DataFrame({'b':[4, 7, -3, 2],'a':[0, 1, 0, 1]})

In [55]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [57]:

frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [58]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

## 排名ranking

In [59]:
obj = Series([7, -5, 7, 4, 2, 0, 4])

In [60]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [61]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [62]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [63]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [64]:
frame = DataFrame(
     {
         'b':[4.3, 7, -3, 2],
         'a':[0, 1, 0, 1],
         'c':[-2, 5, 8, -2.5]
         
     }

)

In [65]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [66]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## 带有重复值的轴索引

In [67]:
obj = Series(range(5), index=list('aabbc'))

In [68]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [69]:
obj.index.is_unique

False

In [70]:
obj['a']

a    0
a    1
dtype: int64

In [71]:
type(obj['a'])

pandas.core.series.Series

In [72]:
obj['c']

4

In [73]:
type(obj['c'])

numpy.int64

In [74]:
obj = DataFrame(np.random.randn(4,3), index=list('aabb'))

In [75]:
obj

0         1         2
a -0.960230  1.149268 -0.482803
a  0.296247 -0.129885 -1.148587
b -1.713989 -0.120554 -1.253912
b  0.369006  2.197526  2.140174

In [76]:
obj.ix['b']

/home/zhanghui/py35/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


0         1         2
b -1.713989 -0.120554 -1.253912
b  0.369006  2.197526  2.140174

In [79]:
obj.loc['b']

0         1         2
b -1.713989 -0.120554 -1.253912
b  0.369006  2.197526  2.140174

## 汇总和计算描述统计

In [80]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=list('abcd'), columns=['one', 'two'])

In [81]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [82]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [83]:
df.sum(axis=1)

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [84]:
df.sum(axis=1, skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

* 达到最大最小值的索引

In [85]:
df.idxmin()

one    d
two    b
dtype: object

In [86]:
df.idxmax()

one    b
two    d
dtype: object

In [87]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [88]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [89]:
list('aabc')*4

['a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c']

In [90]:
obj = Series(list('aabc')*4)

In [91]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [92]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [93]:
df.count()

one    3
two    2
dtype: int64

In [94]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [98]:
df['one'].argmax()

'b'

In [99]:
df.argmax()

AttributeError: 'DataFrame' object has no attribute 'argmax'

* DataFrame 没有argmax函数

In [100]:
df.cumprod()

one   two
a  1.400   NaN
b  9.940 -4.50
c    NaN   NaN
d  7.455  5.85

## 相关系数和协方差

In [101]:
import pandas.io.data as web

ImportError: The pandas.io.data module is moved to a separate package (pandas-datareader). After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.

In [102]:
from pandas_datareader import data, wb

In [103]:
all_data = {}
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG' ]:
    all_data[ticker] = data.get_data_yahoo(ticker,'1/1/2000', '1/1/2010')
price = DataFrame(
        {
            tic:data['Adj Close'] for tic,data in all_data.iteritems()
        }
)    
volume = DataFrame(
            {
            tic:data['Volume'] for tic,data in all_data.iteritems()
                
            }
    )

ConnectionError: HTTPConnectionPool(host='ichart.finance.yahoo.com', port=80): Max retries exceeded with url: /table.csv?b=1&s=AAPL&d=0&a=0&g=d&e=1&c=2000&f=2010&ignore=.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5643ce4a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

* 数据未能获取

## 唯一值、值计数和成员资格

In [104]:
obj = Series(list('cadaabbcc'))

In [105]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [106]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [108]:
obj.count() #统计所有成员的个数

9

In [110]:
obj.value_counts() #统计值出现的次数 注意这时候index变为原来的数值部分，具体的item则变为了该值出现的次数

a    3
c    3
b    2
d    1
dtype: int64

In [111]:
mask = obj.isin(list('bc'))

In [112]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [114]:
obj[mask] #布尔值做筛选条件，False的都删除

0    c
5    b
6    b
7    c
8    c
dtype: object

## 数值出现次数的柱状图

In [115]:
data = DataFrame(
            {
                'Qu1':[1,3,4,3,4],
                'Qu2':[2,3,1,2,3],
                'Qu3':[1,5,2,4,4],
                
                
            }

)

In [116]:

data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [117]:
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

* 测试apply的应用范围

    应用于DataFrame上,应用对象为列或者行

In [119]:
data.apply(lambda x:type(x))

Qu1    <class 'pandas.core.series.Series'>
Qu2    <class 'pandas.core.series.Series'>
Qu3    <class 'pandas.core.series.Series'>
dtype: object

* 应用于Series上，应用对象为元素

In [122]:
data['Qu1'].apply(lambda x:x+1)

0    2
1    4
2    5
3    4
4    5
Name: Qu1, dtype: int64

In [124]:
pd.value_counts(data['Qu1'])

4    2
3    2
1    1
Name: Qu1, dtype: int64

## 处理缺失数据

In [127]:
string_data = Series(['aardvark', 'aitichoke', np.nan, 'avocado'])

In [128]:
string_data

0     aardvark
1    aitichoke
2          NaN
3      avocado
dtype: object

In [129]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [130]:
string_data[0] = None

In [131]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [132]:
string_data.notnull()

0    False
1     True
2    False
3     True
dtype: bool

In [133]:
string_data.dropna()

1    aitichoke
3      avocado
dtype: object

## 滤除缺失数据

In [135]:
data = Series([1, NA, 3.5, NA, 7])

In [136]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [137]:
ss = data.fillna(0)

In [138]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [139]:
ss

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [140]:
data.fillna(0)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [141]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [143]:
data = DataFrame([
    

            [1., 6.5, 3.],
            [1., NA, NA],
            [NA, NA, NA],
            [NA, 6.5, 3.]

    ])

In [144]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [145]:
cleaned = data.dropna()

In [146]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [147]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [148]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [150]:
data.dropna( axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [151]:
df = DataFrame(np.random.randn(7,3))

In [152]:
df

0         1         2
0 -0.273564  0.036788 -0.693476
1 -0.255845 -1.237059 -0.321528
2 -0.890064 -0.387098  0.521945
3  1.633291 -1.256796  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

In [157]:
df.iloc[:4, 1] = NA;df.iloc[:2,2] = NA

In [158]:
df

0         1         2
0 -0.273564       NaN       NaN
1 -0.255845       NaN       NaN
2 -0.890064       NaN       NaN
3  1.633291       NaN  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

In [161]:
df.dropna(thresh=2) # 一行的NA >= thresh ,就删除

0         1         2
3  1.633291       NaN  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

## 填充缺失数据

In [162]:
df.fillna(0)

0         1         2
0 -0.273564  0.000000  0.000000
1 -0.255845  0.000000  0.000000
2 -0.890064  0.000000  0.000000
3  1.633291  0.000000  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

In [163]:
df.fillna({1:0.5,3:111})

0         1         2
0 -0.273564  0.500000       NaN
1 -0.255845  0.500000       NaN
2 -0.890064  0.500000       NaN
3  1.633291  0.500000  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

* 实现填充修改对象本身

In [164]:
df.fillna(0, inplace=True)

In [165]:
df

0         1         2
0 -0.273564  0.000000  0.000000
1 -0.255845  0.000000  0.000000
2 -0.890064  0.000000  0.000000
3  1.633291  0.000000  1.827489
4 -1.627119  0.517427 -1.014662
5  0.296960  1.408358 -0.289359
6 -0.700843  0.693233  0.109619

In [168]:
df = DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA;df.iloc[:2,2] = NA

In [169]:
df

0         1         2
0  0.291144       NaN       NaN
1  0.953188       NaN       NaN
2  1.392189       NaN -0.400689
3 -0.400952       NaN -0.518002
4 -1.206390  0.872318 -0.334372
5  0.818943  0.443963 -1.897554
6  0.509689 -0.922145  0.153510

In [170]:
df.fillna(df.mean())

0         1         2
0  0.291144  0.131379 -0.599421
1  0.953188  0.131379 -0.599421
2  1.392189  0.131379 -0.400689
3 -0.400952  0.131379 -0.518002
4 -1.206390  0.872318 -0.334372
5  0.818943  0.443963 -1.897554
6  0.509689 -0.922145  0.153510

In [172]:
df

0         1         2
0  0.291144       NaN       NaN
1  0.953188       NaN       NaN
2  1.392189       NaN -0.400689
3 -0.400952       NaN -0.518002
4 -1.206390  0.872318 -0.334372
5  0.818943  0.443963 -1.897554
6  0.509689 -0.922145  0.153510

In [175]:
df.fillna(axis=1, method='ffill') # 作用于行，也就是轴向1

0         1         2
0  0.291144  0.291144  0.291144
1  0.953188  0.953188  0.953188
2  1.392189  1.392189 -0.400689
3 -0.400952 -0.400952 -0.518002
4 -1.206390  0.872318 -0.334372
5  0.818943  0.443963 -1.897554
6  0.509689 -0.922145  0.153510

In [184]:
df.fillna(axis=1, method=np.mean(a=1)) #好像填充的时候对列级别的缺乏更多的方法

ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got 1.0

## 层次化索引

In [185]:
data  = Series(np.random.randn(10),
               index=[list('aaabbbccdd'),
                      [1,2,3,1,2,3,1,2,2,3]
                   
               ]
) 

In [186]:
data

a  1   -0.849343
   2    0.070712
   3   -0.175882
b  1    1.054124
   2   -1.069567
   3    0.281714
c  1    0.151159
   2    0.016176
d  2   -1.648331
   3    0.921041
dtype: float64

In [187]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [188]:
data['b']

1    1.054124
2   -1.069567
3    0.281714
dtype: float64

## 层次化索引的选取方法

In [190]:
data.loc[list('bd')]

b  1    1.054124
   2   -1.069567
   3    0.281714
d  2   -1.648331
   3    0.921041
dtype: float64

In [193]:
data

a  1   -0.849343
   2    0.070712
   3   -0.175882
b  1    1.054124
   2   -1.069567
   3    0.281714
c  1    0.151159
   2    0.016176
d  2   -1.648331
   3    0.921041
dtype: float64

In [191]:
data[:,2]

a    0.070712
b   -1.069567
c    0.016176
d   -1.648331
dtype: float64

In [197]:
data[:][6] == data[6]

True

In [194]:
data[:]

a  1   -0.849343
   2    0.070712
   3   -0.175882
b  1    1.054124
   2   -1.069567
   3    0.281714
c  1    0.151159
   2    0.016176
d  2   -1.648331
   3    0.921041
dtype: float64

## 将上述的切片方式应用于DataFrame上

In [199]:
data  = DataFrame(np.random.randn(10,2),
               index=[list('aaabbbccdd'),
                      [1,2,3,1,2,3,1,2,2,3]
                   
               ]
) 

In [200]:
data

0         1
a 1 -1.290133 -0.432969
  2 -1.062394 -1.124182
  3 -0.382635 -1.098075
b 1  1.113085  0.170618
  2 -1.477008 -0.585390
  3  0.350047  0.244728
c 1  1.314524  1.774055
  2 -0.811069 -1.727027
d 2 -0.456927  1.474358
  3  0.290842  0.706298

In [207]:
data.loc[('a',1),0]

-1.290132726079867

In [208]:
data.loc[('a',1)]

0   -1.290133
1   -0.432969
Name: (a, 1), dtype: float64

In [210]:
data.loc['a']

0         1
1 -1.290133 -0.432969
2 -1.062394 -1.124182
3 -0.382635 -1.098075

In [212]:
data.loc['a'][1]

1   -0.432969
2   -1.124182
3   -1.098075
Name: 1, dtype: float64

In [213]:
data.iloc[6]

0    1.314524
1    1.774055
Name: (c, 1), dtype: float64

### 临时补充：iloc和loc的区别

In [268]:
data1 = data.swaplevel(0,1).sort_index(level=0)
data1

0         1
1 a -1.290133 -0.432969
  b  1.113085  0.170618
  c  1.314524  1.774055
2 a -1.062394 -1.124182
  b -1.477008 -0.585390
  c -0.811069 -1.727027
  d -0.456927  1.474358
3 a -0.382635 -1.098075
  b  0.350047  0.244728
  d  0.290842  0.706298

* iloc

In [271]:
data1.iloc[(1,'a')]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [272]:
data1.iloc[(1,1)]

0.17061787804494732

In [273]:
data1.iloc[1,1]

0.17061787804494732

* loc

In [269]:
data1.loc[1]

0         1
a -1.290133 -0.432969
b  1.113085  0.170618
c  1.314524  1.774055

In [276]:
data1.loc[(1,'a')]

0   -1.290133
1   -0.432969
Name: (1, a), dtype: float64

In [275]:
data1.loc[(1,'a'),1]

-0.43296865943318535

In [281]:
data  = Series(np.random.randn(10),
               index=[list('aaabbbccdd'),
                      [1,2,3,1,2,3,1,2,2,3]
                   
               ]
) 
data

a  1    0.000981
   2    1.296490
   3    1.813286
b  1   -1.772852
   2   -0.407201
   3    1.159183
c  1    0.876773
   2   -1.103964
d  2   -1.029267
   3   -0.816428
dtype: float64

In [282]:
data.unstack()

1         2         3
a  0.000981  1.296490  1.813286
b -1.772852 -0.407201  1.159183
c  0.876773 -1.103964       NaN
d       NaN -1.029267 -0.816428

In [283]:
frame = DataFrame(np.arange(12).reshape((4,3)),
                  index=[list('aabb'), [1,2,1,2]],
                  columns=['Ohio,Ohio,Colorado'.split(',') , 'green,red,green'.split(',')]
                  


)

In [284]:
frame

Ohio     Colorado
    green red    green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [286]:
frame.index.names = 'key1,key2'.split(',')

In [287]:
frame.columns.names = 'state,color'.split(',')

In [288]:
frame

state      Ohio     Colorado
color     green red    green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [289]:
frame.columns

MultiIndex(levels=[['Colorado', 'Ohio'], ['green', 'red']],
           labels=[[1, 1, 0], [0, 1, 0]],
           names=['state', 'color'])

In [291]:
data.unstack().columns

Int64Index([1, 2, 3], dtype='int64')

In [292]:
frame

state      Ohio     Colorado
color     green red    green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [293]:
frame.sum(level='key2')

state  Ohio     Colorado
color green red    green
key2                    
1         6   8       10
2        12  14       16

In [297]:
frame.sum(level='color',axis = 1)

color      green  red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

## 使用DataFrame的列

In [298]:
frame = DataFrame(
       {
           'a':range(7),
           'b':range(7,0,-1),
           'c':'one,one,one,two,two,two,two'.split(','),
           'd':[0,1,2,0,1,2,3]
       }


)

In [299]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [311]:
frame2 = frame.set_index(['c', 'd'])

In [312]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [309]:
frame3 = frame.set_index(['c', 'd'], drop=False)

In [310]:
frame3

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [313]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## 整数索引

In [315]:
ser = Series(np.arange(3.))

In [316]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [317]:
ser[-1]

KeyError: -1

In [320]:
ser.ix[:1]

0    0.0
1    1.0
dtype: float64

## 补充：range内置函数的使用

In [302]:
list(range(7,0,-2)) # 从7开始

[7, 5, 3, 1]

In [303]:
list(range(8,0,-2))

[8, 6, 4, 2]

## 补充：index是数字，切片选取的方法的实际效果

In [255]:
s=Series([1,2,34,3,4,4345,5], index=[1,3,2,4,6,8,0])

In [256]:
s[2]

34

* 按照实际的index

In [257]:
s = Series([1,2,34,3,4,4345,5], index=[list('1324680')])

In [258]:
s[5]

4345

In [259]:
s['1']

1