## 第一部分

In [1]:
data1=[6,7.5,8,0,1]

In [124]:
import numpy as np
import pandas as pd
from numpy.random import randn
from numpy.linalg import inv,qr, eig ,det ,svd

import matplotlib.pyplot as plt
import random

In [3]:
data1=np.array(data1)

In [4]:
data1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data1.shape


(5,)

In [6]:
data1.dtype


dtype('float64')

In [7]:
data2=[(1,2,3,4),(2,3,4,5)]

In [8]:
data2=np.array(data2)

In [9]:
data2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [10]:
data2.ndim

2

In [11]:
data3=[((1,1),(2,2),(3,2),(4,2)),(2,3,4,5)]

In [12]:
data3=np.array(data3)
data3

array([[(1, 1), (2, 2), (3, 2), (4, 2)],
       [2, 3, 4, 5]], dtype=object)

In [13]:
data3.ndim

2

In [14]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(15).astype(np.int8)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int8)

In [18]:
data3

array([[(1, 1), (2, 2), (3, 2), (4, 2)],
       [2, 3, 4, 5]], dtype=object)

In [19]:
data2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [20]:
data1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [21]:
data1.dtype

dtype('float64')

In [22]:
data1_=data1*data

NameError: name 'data' is not defined

In [ ]:
data1_

In [ ]:
data1

In [ ]:
data1[2:6]

In [ ]:
_i33

In [ ]:
data1[2:4]=11

In [ ]:
data1

In [ ]:
arr2d=np.array([[1,2,3],[1,2,3],[1,2,31]])

In [ ]:
arr2d[0,2]

In [ ]:
arr2d[0][2]

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr3d


In [ ]:
arr3d[0]

In [ ]:
old_values=arr3d[0].copy()

In [ ]:
old_values_1=arr3d[0]#好像也复制

In [ ]:
old_values_1=42


In [ ]:
arr3d

In [ ]:
arr3d

In [ ]:
arr2d

In [ ]:
arr2d[:2,1:]

In [ ]:

names=np.array(['Bob','joe','will','bob','will','joe','joe'])

In [ ]:
from numpy.random import randn
data=randn(7,4)

In [ ]:
data

In [ ]:

names=='bob'

In [ ]:
data[names=='bob']

In [ ]:
data[names=='bob',2:]

In [ ]:
mask=(names=='bob')|(names=='will')

In [ ]:
data[mask]

In [ ]:
arr=np.empty((8,4))

In [ ]:
for i in range(8):
    arr[i]=i

In [ ]:
arr

In [ ]:

arr[[1,2,0]]

In [ ]:
_[[0,1,2],:]

In [ ]:
arr=np.arange(32).reshape((8,4))

In [ ]:
arr

In [ ]:

arr[[1,5,7,2],[0,3,1,2]]

In [ ]:
arr[[1,5,7,2]]

In [ ]:
_[[0,3,1,2]]

In [ ]:
arr[[1,5,7,2]][:,[0,3,1,2]]

In [ ]:
arr[np.ix_([1,5,7],[1,2])]

In [24]:
data=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
data.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [26]:
data

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
data.T[1]=434343

In [28]:
data

array([[[     1, 434343,      3],
        [     4, 434343,      6]],

       [[     7, 434343,      9],
        [    10, 434343,     12]]])

In [29]:
arr=np.random.randn(6,3)

In [30]:
np.dot(arr.T,arr)

array([[  5.64397268,   4.21015737,   1.43447295],
       [  4.21015737,   6.05026522,  -3.93825769],
       [  1.43447295,  -3.93825769,  10.14638337]])

In [5]:
arr=np.arange(16).reshape((2,2,4))

In [6]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [35]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr = np.arange(10)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [13]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [14]:
x = y = randn(8)

NameError: name 'randn' is not defined

In [20]:
x = y = np.arange(10)

In [17]:
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.maximum(x,arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x_df = pd.DataFrame(x)

In [26]:
x_df

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [27]:
q, w =np.modf(x_df)

In [28]:
q

0
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0
5  0.0
6  0.0
7  0.0
8  0.0
9  0.0

In [29]:
w

0
0  0.0
1  1.0
2  2.0
3  3.0
4  4.0
5  5.0
6  6.0
7  7.0
8  8.0
9  9.0

In [34]:
np.ceil(x_df)

0
0  0.0
1  1.0
2  2.0
3  3.0
4  4.0
5  5.0
6  6.0
7  7.0
8  8.0
9  9.0

In [35]:
np.rint(x_df)

0
0  0.0
1  1.0
2  2.0
3  3.0
4  4.0
5  5.0
6  6.0
7  7.0
8  8.0
9  9.0

In [36]:
-x_df

0
0  0
1 -1
2 -2
3 -3
4 -4
5 -5
6 -6
7 -7
8 -8
9 -9

In [38]:
y_df = pd.DataFrame(y)
x_df.add(y_df)

0
0   0
1   2
2   4
3   6
4   8
5  10
6  12
7  14
8  16
9  18

In [39]:
x_df = x_df.add(y_df)

In [44]:
x.max()

9

In [4]:
points = np.arange(-5,5,0.01)

In [5]:
xs, ys = np.meshgrid(points,points)

In [6]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [7]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [9]:
z =  np.sqrt(xs ** 2 + ys ** 2)

In [10]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [19]:
plt.imshow(z ); 
plt.colorbar()

In [17]:


plt.title('1')

In [20]:
cond= [True]

In [21]:
np.where(cond , 1 ,2)

array([1])

In [25]:
arr = randn(4,4)

In [26]:
arr

array([[-0.17283545, -0.90454965,  1.01533159, -0.3649477 ],
       [ 2.0829824 , -0.27802588, -1.36707891,  0.63202273],
       [-1.98538024, -2.05890181,  2.50221579, -0.43553291],
       [-0.59163796, -0.50866757,  0.05192914, -0.35772638]])

In [27]:
arr >0 

array([[False, False,  True, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False]], dtype=bool)

In [28]:
np.where(_,2,-1)

array([[-1, -1,  2, -1],
       [ 2, -1, -1,  2],
       [-1, -1,  2, -1],
       [-1, -1,  2, -1]])

In [29]:
arr= randn(5,4)

In [30]:
arr

array([[-0.98095572,  0.35294669, -0.91816609, -2.17272086],
       [ 0.77752773,  0.54234422, -1.79486168,  2.67628004],
       [-0.68374992, -0.41786015, -0.33391408,  1.15633999],
       [ 0.12302924,  0.52909192,  1.37086321, -0.75559742],
       [-1.2889836 , -0.54081193,  0.13467451,  1.56316242]])

In [31]:
arr.mean()

-0.033068074124322278

In [32]:
np.mean(arr)

-0.033068074124322278

In [33]:
arr.sum()

-0.66136148248644555

In [36]:
arr.sum(axis =1)

array([-3.71889597,  2.20129031, -0.27918417,  1.26738695, -0.13195861])

In [39]:
arr[0].sum()

-3.7188959696460215

In [40]:
arr[0]

array([-0.98095572,  0.35294669, -0.91816609, -2.17272086])

In [66]:
a = np.arange(12)




In [70]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a.sum(axis = 0)

array([12, 15, 18, 21])

In [69]:
a.sum(axis = 1)

array([ 6, 22, 38])

In [4]:
arr = np.arange(12)

In [5]:
arr = arr.reshape(3,4)

In [6]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr.sum(axis = 1)

array([ 6, 22, 38])

In [9]:
arr.cumsum(1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [10]:
arr.cumprod(0)

array([[  0,   1,   2,   3],
       [  0,   5,  12,  21],
       [  0,  45, 120, 231]])

In [11]:
arr.std(0)

array([ 3.26598632,  3.26598632,  3.26598632,  3.26598632])

In [12]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
arr.std(1)

array([ 1.11803399,  1.11803399,  1.11803399])

In [14]:
arr.min()

0

In [15]:
arr.min(1)

array([0, 4, 8])

In [16]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr.min(0)

array([0, 1, 2, 3])

In [18]:
arr = randn(100)

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr = randn(100)

In [24]:
arr

array([  7.13393903e-01,  -4.51191621e-01,   6.49448030e-01,
        -1.67833991e+00,   8.68628177e-01,  -2.67077495e-01,
         1.11215165e+00,  -5.85282276e-01,  -5.29280568e-01,
        -2.00280929e+00,  -9.32286767e-01,   2.41461407e-01,
         6.71698857e-01,   1.56174009e-01,   9.33045593e-01,
         6.49069576e-01,   1.29914014e+00,  -2.12733388e-01,
        -1.09284620e+00,  -1.73084223e+00,   4.32039178e-01,
         2.85198346e-01,   8.45507189e-01,   2.21817520e-01,
        -1.54833741e+00,   1.30981793e+00,   8.99374109e-01,
        -2.19053570e-04,  -3.62908643e-02,  -7.15748695e-01,
         5.70891040e-01,  -7.96579928e-01,  -1.22991099e+00,
        -6.48007551e-01,  -1.06591790e-01,  -1.24346968e+00,
        -1.22639866e+00,   1.47908778e+00,   9.48411848e-01,
         2.22024428e+00,   2.99426880e-01,   6.12794974e-01,
         6.24179728e-01,  -7.03821274e-01,  -2.37750574e-01,
         1.58431942e+00,   2.46350774e+00,  -9.74715858e-01,
         1.67406138e+00,

In [25]:

(arr>0).sum()

55

In [26]:
arr.all()

True

In [27]:
arr.any()

True

In [32]:
arr= randn(8)

In [33]:
arr

array([ 1.70381147,  0.94879863, -0.10955938,  0.3805486 , -1.56009135,
        0.1036621 , -0.61509251,  2.29093322])

In [34]:
arr.sort()

In [35]:
arr

array([-1.56009135, -0.61509251, -0.10955938,  0.1036621 ,  0.3805486 ,
        0.94879863,  1.70381147,  2.29093322])

In [39]:
arr = randn(3,4)

In [40]:
arr

array([[ 0.37600272,  2.04748003, -0.03017451, -0.76028927],
       [ 0.54235282,  2.08221263,  0.48813766, -1.89410167],
       [ 0.06004015, -0.30382996,  0.80194957,  1.18304413]])

In [41]:
arr.sort(1)

In [42]:
arr

array([[-0.76028927, -0.03017451,  0.37600272,  2.04748003],
       [-1.89410167,  0.48813766,  0.54235282,  2.08221263],
       [-0.30382996,  0.06004015,  0.80194957,  1.18304413]])

In [43]:
names = ['will','will','will','Bob','Bob']

In [44]:
names_np = np.array(names)

In [45]:
names_np

array(['will', 'will', 'will', 'Bob', 'Bob'], 
      dtype='<U4')

In [47]:
np.unique(names_np)

array(['Bob', 'will'], 
      dtype='<U4')

In [48]:
np.in1d(names_np , ['will'])

array([ True,  True,  True, False, False], dtype=bool)

In [49]:
arr = np.arange(10
               )

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.save('test_npy',arr)

In [52]:
! ls

chapter1_data.txt		      Python_data_analysis_chapter_3.ipynb
movies.dat			      ratings.dat
names				      README
Python_data_analysis_chapter_1.ipynb  test_npy.npy
Python_data_analysis_chapter_2.ipynb  users.dat


In [54]:
np.load('test_npy.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.savez('dual_test_npy',a= arr,b=arr)

In [61]:
! ls

chapter1_data.txt  Python_data_analysis_chapter_1.ipynb  README
dual_test_npy.npz  Python_data_analysis_chapter_2.ipynb  test_npy.npy
movies.dat	   Python_data_analysis_chapter_3.ipynb  users.dat
names		   ratings.dat


In [63]:
npz = np.load('dual_test_npy.npz')

In [64]:
npz

In [67]:
npz.items()

[('b', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])),
 ('a', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))]

In [68]:
npz.keys()

['b', 'a']

In [71]:
arr = np.arange(12) 

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
np.savetxt ('arr.txt',arr,delimiter= ':')

In [76]:
! ls

arr.txt		   names				 ratings.dat
chapter1_data.txt  Python_data_analysis_chapter_1.ipynb  README
dual_test_npy.npz  Python_data_analysis_chapter_2.ipynb  test_npy.npy
movies.dat	   Python_data_analysis_chapter_3.ipynb  users.dat


In [77]:
np.loadtxt('arr.txt')

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.])

In [82]:
x = np.arange(1,7)

In [83]:
x

array([1, 2, 3, 4, 5, 6])

In [84]:
x = x.reshape(2,3)

In [85]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
y=np.arange(7,13).reshape(3,2)

In [87]:
y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [88]:
x.dot(y)

array([[ 58,  64],
       [139, 154]])

In [91]:
x= randn(5,5)

In [92]:
x

array([[ 0.94040073,  1.26129693,  0.66511393, -0.65249086,  0.74021075],
       [-0.0759105 ,  0.91641897, -2.63416104,  0.31600942,  0.08476629],
       [-1.09540215,  0.40793367,  0.42123249,  1.2139218 , -0.28260489],
       [-1.47691132,  1.53078155, -0.36094119, -0.36819645, -1.53371083],
       [-1.21141894,  0.40796704, -2.23245764,  0.93703694, -1.20470235]])

In [104]:
mat = x.T.dot(x)
mat

array([[  5.7388247 ,  -2.08534029,   3.60153474,  -2.55867465,
          4.72378021],
       [ -2.08534029,   5.10683279,  -2.86654533,  -0.21953625,
         -1.94323216],
       [  3.60153474,  -2.86654533,  12.67276339,  -2.71405517,
          3.39302045],
       [ -2.55867465,  -0.21953625,  -2.71405517,   3.01281926,
         -1.36339775],
       [  4.72378021,  -1.94323216,   3.39302045,  -1.36339775,
          4.43853946]])

In [97]:
inv(mat)

array([[ 9.48791698,  1.37008273,  1.05278951,  5.16111372, -8.71726646],
       [ 1.37008273,  0.47600837,  0.21096319,  0.8708138 , -1.14350944],
       [ 1.05278951,  0.21096319,  0.24039857,  0.67087835, -1.00578108],
       [ 5.16111372,  0.8708138 ,  0.67087835,  3.29577389, -4.61201864],
       [-8.71726646, -1.14350944, -1.00578108, -4.61201864,  8.35431717]])

In [105]:
eig(mat)

(array([ 18.53897398,   6.2579883 ,   0.04814759,   4.59458311,   1.53008663]),
 array([[ 0.43747466, -0.56929143, -0.67341824,  0.17446466, -0.02435458],
        [-0.27542138,  0.14550978, -0.09754436,  0.84738574,  0.41879884],
        [ 0.73059751,  0.66122972, -0.07838698,  0.04330476,  0.14485413],
        [-0.22950225,  0.07910806, -0.37210852, -0.49880336,  0.74417813],
        [ 0.3825114 , -0.45962088,  0.62640538,  0.02862513,  0.49922998]]))

In [106]:
q , r = qr(mat)

In [107]:
q

array([[-0.64519993, -0.20453921,  0.30521728,  0.00837426, -0.66981569],
       [ 0.23444895, -0.88297744, -0.28125228, -0.28028818, -0.08786476],
       [-0.40491042,  0.21454262, -0.87878965, -0.10851387, -0.07728202],
       [ 0.2876646 ,  0.34417238,  0.08343492, -0.81624121, -0.35437742],
       [-0.53108133, -0.11845414,  0.22024291, -0.49329853,  0.64192746]])

In [108]:
r

array([[ -8.89464564,   4.67230855, -10.70980987,   4.28909241,
         -7.62666741],
       [  0.        ,  -4.54305487,   3.17726749,   1.33334362,
          0.48257217],
       [  0.        ,   0.        ,  -8.7103785 ,   1.6169726 ,
         -0.12963157],
       [  0.        ,   0.        ,   0.        ,  -1.45200608,  -0.8606302 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.07683781]])

In [109]:
q

array([[-0.64519993, -0.20453921,  0.30521728,  0.00837426, -0.66981569],
       [ 0.23444895, -0.88297744, -0.28125228, -0.28028818, -0.08786476],
       [-0.40491042,  0.21454262, -0.87878965, -0.10851387, -0.07728202],
       [ 0.2876646 ,  0.34417238,  0.08343492, -0.81624121, -0.35437742],
       [-0.53108133, -0.11845414,  0.22024291, -0.49329853,  0.64192746]])

In [110]:
svd(mat)

(array([[-0.43747466, -0.56929143, -0.17446466, -0.02435458,  0.67341824],
        [ 0.27542138,  0.14550978, -0.84738574,  0.41879884,  0.09754436],
        [-0.73059751,  0.66122972, -0.04330476,  0.14485413,  0.07838698],
        [ 0.22950225,  0.07910806,  0.49880336,  0.74417813,  0.37210852],
        [-0.3825114 , -0.45962088, -0.02862513,  0.49922998, -0.62640538]]),
 array([ 18.53897398,   6.2579883 ,   4.59458311,   1.53008663,   0.04814759]),
 array([[-0.43747466,  0.27542138, -0.73059751,  0.22950225, -0.3825114 ],
        [-0.56929143,  0.14550978,  0.66122972,  0.07910806, -0.45962088],
        [-0.17446466, -0.84738574, -0.04330476,  0.49880336, -0.02862513],
        [-0.02435458,  0.41879884,  0.14485413,  0.74417813,  0.49922998],
        [ 0.67341824,  0.09754436,  0.07838698,  0.37210852, -0.62640538]]))

In [111]:
samples = np.random.normal(size=(4,4))

In [112]:
samples

array([[-2.14232447,  0.80221164, -0.41343204,  0.32669883],
       [ 1.86594917, -0.60896999,  0.37713409,  0.55389768],
       [-0.0780426 ,  1.15320268,  0.41941179,  0.86454982],
       [-0.40525866, -0.04325301, -0.12705073, -0.5848155 ]])

In [113]:
from random import normalvariate

In [114]:
N=1000000

In [116]:
%timeit samples = [normalvariate(0,1) for i in range(N)]

677 ms ± 6.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [117]:
%timeit np.random.normal(N)

1.33 µs ± 17 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [118]:

np.random.binomial()

TypeError: binomial() takes at least 2 positional arguments (0 given)

In [119]:

np.random.rand(10)

array([ 0.83356839,  0.92891495,  0.48843032,  0.93487917,  0.19079479,
        0.4123163 ,  0.07465196,  0.50339263,  0.69559063,  0.6037727 ])

In [123]:

np.random.gamma(10)

5.563484490562083

## 随机漫步

In [143]:
random.randint(-1,1)

0

In [144]:
position = 0
walk= []
for i in range(1000):
    position += 1 if random.randint(0,1) else -1
    walk.append(position)

In [145]:
walk

[-1,
 0,
 -1,
 0,
 1,
 0,
 -1,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -3,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 0,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,
 -5,
 -6,
 -5,
 -4,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 -2,
 -3,
 -4,
 -3,
 -2,
 -3,
 -2,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 -1,
 0,
 -1,
 0,
 1,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 5,
 4,
 3,
 4,
 5,
 6,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 6,
 7,
 6,
 5,
 4,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 4,
 5,
 4,
 3,
 2,
 1,
 0,
 1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 1,
 2,
 3,

In [146]:
nsteps =1000

In [147]:
draws = np.random.randint(0,2,size = nsteps)

In [148]:
draws

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1,

In [166]:
np.random.randint(0,2)

0

In [172]:
random.randint(0,2)

2

In [173]:
steps = np.where(draws >0 ,1,-1)

In [174]:
steps

array([-1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1,
       -1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,
        1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1,
       -1,  1,  1, -1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1,
        1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,
        1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1,
        1, -1, -1,  1,  1

In [175]:
walk = steps.cumsum()

In [176]:
walk

array([ -1,  -2,  -3,  -2,  -1,   0,   1,   0,   1,   2,   1,   0,   1,
         0,  -1,  -2,  -3,  -4,  -5,  -6,  -5,  -6,  -5,  -6,  -7,  -8,
        -7,  -6,  -7,  -8,  -9, -10,  -9,  -8,  -9,  -8,  -9,  -8,  -9,
       -10,  -9, -10,  -9,  -8,  -9,  -8,  -7,  -6,  -5,  -4,  -5,  -6,
        -7,  -6,  -5,  -6,  -5,  -6,  -5,  -6,  -5,  -4,  -5,  -4,  -3,
        -2,  -1,   0,   1,   0,   1,   2,   1,   2,   1,   2,   1,   2,
         1,   0,   1,   0,  -1,  -2,  -3,  -4,  -3,  -2,  -1,   0,  -1,
        -2,  -3,  -4,  -5,  -4,  -3,  -2,  -1,   0,   1,   0,  -1,  -2,
        -3,  -2,  -3,  -4,  -5,  -6,  -7,  -6,  -7,  -6,  -7,  -8,  -9,
       -10, -11, -12, -13, -12, -11, -12, -11, -10,  -9, -10,  -9, -10,
        -9, -10, -11, -12, -11, -10, -11, -10,  -9, -10,  -9, -10, -11,
       -10, -11, -10, -11, -10,  -9, -10,  -9, -10,  -9, -10,  -9, -10,
        -9, -10,  -9, -10,  -9, -10,  -9, -10, -11, -12, -11, -10, -11,
       -12, -11, -10,  -9, -10, -11, -12, -13, -12, -13, -12, -1

In [178]:
np.abs(walk)>= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,

In [179]:
_.argmax()

31

In [180]:
nwalks = 5000
nsteps = 1000

In [181]:
draws = np.random.randint(0,2,size=(nwalks , nsteps))


In [200]:
for i in range(100):
    pass
#     print(np.random.randint(8))

In [203]:
steps = np.where(draws >0 ,1,-1)

In [204]:
walks = steps.cumsum(1)

In [205]:
walks

array([[  1,   0,   1, ..., -44, -45, -46],
       [  1,   2,   3, ..., -68, -69, -70],
       [  1,   0,  -1, ...,  10,  11,  10],
       ..., 
       [ -1,  -2,  -3, ...,   6,   5,   4],
       [ -1,  -2,  -3, ...,  30,  31,  30],
       [ -1,  -2,  -3, ...,   2,   1,   0]])

In [206]:

walks.argmax(1)

array([ 47, 109, 815, ..., 584, 768, 800])

In [211]:
walks[0][48]

11

In [215]:
hits30 = (np.abs(walks >=30)).any(1)

In [216]:
hits30

array([False, False,  True, ..., False,  True, False], dtype=bool)

In [217]:
_.sum()

1686

In [218]:
 (np.abs(walks[hits30]>=30)).argmax(1)

array([755, 349, 349, ..., 741, 321, 125])

In [220]:
s =np.arange(12).reshape(3,4)

In [221]:
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
bo = [True,True,False]

In [223]:
s[bo]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [224]:
_.mean()

3.5

In [225]:
steps = np.random.normal(loc = 0 , scale =0.25, size=(nwalks ,nsteps))

In [226]:
steps.cumsum()

array([  -0.19409426,   -0.41437293,   -0.64310327, ..., -161.22805155,
       -161.24697678, -161.36059542])